#
# examples Makefile
#

TOPDIR= ../

# Libraries
include $(TOPDIR)/Makefile.lib.incl
CXXFLAGS+= ${LIB_EXPERIMENT_FLAGS}
LIBS+= ${LIB_EXPERIMENT_LIBS}

# Targets
MAKE_EXES=1
include $(TOPDIR)/Make/Makefile.incl
